apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u8bkemo82-nodejs
  janus-idp.io/tekton: u8bkemo82-nodejs
  backstage.io/kubernetes-id: u8bkemo82-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8bkemo82-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
